//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//

class ___FILEBASENAMEASIDENTIFIER___Interactor: InteractorProtocolBase{
    typealias PresenterType = protocol<___FILEBASENAMEASIDENTIFIER___PresenterProtocolInteractor>
    
    weak var presenter:___FILEBASENAMEASIDENTIFIER___PresenterProtocolInteractor?
    
    required init() {
    }
}

extension ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___InteractorProtocolPresenter {
    
}