//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIPER Swift Xcode Templates
//


protocol ___FILEBASENAMEASIDENTIFIER___PresenterProtocolView: PresenterProtocolViewBase {
    func viewLoaded()
}

protocol ___FILEBASENAMEASIDENTIFIER___PresenterProtocolInteractor: PresenterProtocolInteractorBase {
    
}
